version: "3"
services: 
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - "27017:27017"

  url-shortener:
    build: .
    image: url-shortener:1.1
    container_name: url-shortener
    ports: 
      - "5000:5000"
    links: 
      - mongo
    depends_on: 
      - mongo
    restart: on-failure
      
networks:
  network:
    driver: bridge